version: '3.0'

services:
  grafana:
    container_name: 'grafana-databend-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-10.1.0}
    network_mode: host
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-databend-datasource
      - ./provisioning:/etc/grafana/provisioning
